setClass("InputFileFormat", contains = "EnumValue")

InputFileFormatValues = structure(c(0L, 1L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, 10L, 11L, 12L, 13L, 14L, 15L, 16L, 17L, 18L), .Names = c('IFF_UNKNOWN', 'IFF_BMP', 'IFF_JFIF_JPEG', 'IFF_PNG', 'IFF_TIFF', 'IFF_TIFF_PACKBITS', 'IFF_TIFF_RLE', 'IFF_TIFF_G3', 'IFF_TIFF_G4', 'IFF_TIFF_LZW', 'IFF_TIFF_ZIP', 'IFF_PNM', 'IFF_PS', 'IFF_GIF', 'IFF_JP2', 'IFF_WEBP', 'IFF_LPDF', 'IFF_DEFAULT', 'IFF_SPIX'))

`IFF_UNKNOWN` = GenericEnumValue('IFF_UNKNOWN', 0L, 'InputFileFormat')
`IFF_BMP` = GenericEnumValue('IFF_BMP', 1L, 'InputFileFormat')
`IFF_JFIF_JPEG` = GenericEnumValue('IFF_JFIF_JPEG', 2L, 'InputFileFormat')
`IFF_PNG` = GenericEnumValue('IFF_PNG', 3L, 'InputFileFormat')
`IFF_TIFF` = GenericEnumValue('IFF_TIFF', 4L, 'InputFileFormat')
`IFF_TIFF_PACKBITS` = GenericEnumValue('IFF_TIFF_PACKBITS', 5L, 'InputFileFormat')
`IFF_TIFF_RLE` = GenericEnumValue('IFF_TIFF_RLE', 6L, 'InputFileFormat')
`IFF_TIFF_G3` = GenericEnumValue('IFF_TIFF_G3', 7L, 'InputFileFormat')
`IFF_TIFF_G4` = GenericEnumValue('IFF_TIFF_G4', 8L, 'InputFileFormat')
`IFF_TIFF_LZW` = GenericEnumValue('IFF_TIFF_LZW', 9L, 'InputFileFormat')
`IFF_TIFF_ZIP` = GenericEnumValue('IFF_TIFF_ZIP', 10L, 'InputFileFormat')
`IFF_PNM` = GenericEnumValue('IFF_PNM', 11L, 'InputFileFormat')
`IFF_PS` = GenericEnumValue('IFF_PS', 12L, 'InputFileFormat')
`IFF_GIF` = GenericEnumValue('IFF_GIF', 13L, 'InputFileFormat')
`IFF_JP2` = GenericEnumValue('IFF_JP2', 14L, 'InputFileFormat')
`IFF_WEBP` = GenericEnumValue('IFF_WEBP', 15L, 'InputFileFormat')
`IFF_LPDF` = GenericEnumValue('IFF_LPDF', 16L, 'InputFileFormat')
`IFF_DEFAULT` = GenericEnumValue('IFF_DEFAULT', 17L, 'InputFileFormat')
`IFF_SPIX` = GenericEnumValue('IFF_SPIX', 18L, 'InputFileFormat')

 setAs("character", "InputFileFormat", function(from) asEnumValue(from, InputFileFormatValues, "InputFileFormat", prefix = "IFF_") )
 setAs("integer", "InputFileFormat", function(from) asEnumValue(from, InputFileFormatValues, "InputFileFormat", prefix = "IFF_") )
 setAs("numeric", "InputFileFormat", function(from) asEnumValue(from, InputFileFormatValues, "InputFileFormat", prefix = "IFF_") )
